# Generated by Django 4.2.5 on 2025-09-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizing_Committee',
            fields=[
                ('unique_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('member_Name', models.CharField(max_length=100)),
                ('member_Role', models.CharField(max_length=100)),
                ('member_Department', models.CharField(max_length=100)),
                ('member_YOG', models.IntegerField()),
                ('member_InstaID', models.URLField(max_length=100)),
                ('member_Pic', models.ImageField(blank=True, null=True, upload_to='member_pics/')),
            ],
        ),
    ]
